steps:

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - create_question
    - --gen2
    - --region=us-central1
    - --source=./src/question_creator_cloud_function
    - --trigger-http
    - --runtime=python311

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - questions_to_datawarehouse
    - --gen2
    - --region=us-central1
    - --source=./src/questions_to_datawarehouse_cloud_function
    - --trigger-http
    - --runtime=python311

options:
  logging: CLOUD_LOGGING_ONLY