steps:

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - create_question
    - --gen2
    - --region=us-central1
    - --source=./src
    - --entry-point=questions_creator
    - --trigger-http
    - --runtime=python311

options:
  logging: CLOUD_LOGGING_ONLY